src/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_blog, name='blogs'),
    path('create', views.blog_create, name='blog-create'),
    path('<int:id>/', views.blog_detail, name='blog-detail'),
    path('<int:id>/update', views.blog_update, name='blog-update'),
    path('<int:id>/delete', views.blog_delete, name='blog-delete'),
    path('author/<int:id>', views.author_detail, name='author-detail'),
    path('like/<int:id>/', views.blog_like, name='blog-like'),
]

src/openSourceBookHub/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_library.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

from ckeditor.fields import RichTextField


class Blog(models.Model):
    """
    Model representing a blog post.
    """
    title = models.CharField(max_length=200)
    content = RichTextField(null=True, blank=True,
                            config_name="special", external_plugin_resources=[(
                                'youtube', '/static/shareledge/ckeditor-plugins/youtube/youtube/', 'plugin.js',
                            )])
    thumbnail = models.ImageField(
        upload_to='blogs/thumbnails/', null=True, blank=True)
    author = models.ForeignKey(
        'BlogAuthor', on_delete=models.SET_NULL, null=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-publish_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_like_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-like', args=[str(self.id)])

    @property
    def get_comment_count(self):
        return self.blogcomment_set.all().count()

    @property
    def get_view_count(self):
        return self.blogview_set.all().count()

    @property
    def get_like_count(self):
        return self.bloglike_set.all().count()


class BlogAuthor(models.Model):
    """
    Model representing a blog author.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(
        max_length=400, help_text="Enter your bio details here.")

    class Meta:
        ordering = ["user", "bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.TextField(
        max_length=1000, help_text="Enter comment about blog here.")
    commenter = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 70
        if len(self.content) > len_title:
            titlestring = self.content[:len_title] + '...'
        else:
            titlestring = self.content
        return titlestring


class BlogView(models.Model):
    """
    No of view associated with a blog
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class BlogLike(models.Model):
    """
    Like assocated with a blog
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def user_is_created(sender, instance, created, **kwargs):
    """ When any user instance created, FileUploader object
    instance is created and automatically linked by User """
    if created:
        BlogAuthor.objects.create(user=instance)
    else:
        instance.blogauthor.save()

src/blog/forms.py
from django import forms
from .models import Blog, BlogComment


class BlogForm(forms.ModelForm):
    """Respresenting Blog Form"""
    class Meta:
        model = Blog
        fields = ('title', 'thumbnail', 'content')

    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        self.fields['thumbnail'].required = False


class CommentForm(forms.ModelForm):
    """Respresenting comment form"""
    content = forms.CharField(required=True, widget=forms.Textarea(attrs={
            'rows': 4
        }))
    class Meta:
        model  = BlogComment
        fields = ('content',)

src/blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
# Create your views here.
from .forms import BlogForm, CommentForm
from .models import Blog, BlogAuthor, BlogLike, BlogView


def list_blog(request):
    """Blog list view"""
    blog_list = Blog.objects.all()
    context = {
        'blog_list': blog_list
    }
    return render(request, 'blog/blog-list.html', context)


# @login_required
def blog_create(request):
    """posting a blog"""
    form = BlogForm()
    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            author = get_object_or_404(BlogAuthor, user=request.user)
            form.instance.author =  author    
            form.save()
            id= form.instance.id
            return redirect('blog-detail', id=id)
            # return redirect('blogs')
    context = {
        'form': form
    }
    return render(request, 'blog/blog-create.html', context)


def blog_detail(request, id):
    # Comment view
    blog = get_object_or_404(Blog, id=id)
    if request.user.is_authenticated:
        BlogView.objects.get_or_create(user=request.user, blog=blog)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.commenter = request.user
            form.instance.blog = blog
            form.save()
        return redirect('blog-detail', id=id)
    else:
        form = CommentForm()
    context = {
        'blog': blog,
        'form': form
    }
    return render(request, 'blog/blog-detail.html', context)


def blog_update(request, id):
    """update a blog"""
    blog = get_object_or_404(Blog, id=id)
    form = BlogForm(request.POST or None, request.FILES or None, instance=blog)
    if form.is_valid():
        author = get_object_or_404(BlogAuthor, user=request.user)
        form.instance.author =  author    
        form.save()
        return redirect('blog-detail', id=id)
    context = {
        'form': form,
        'blog': blog
    }
    return render(request, 'blog/blog-update.html', context)


def blog_delete(request, id):
    """delete a blog"""
    blog = get_object_or_404(Blog, id=id)
    blog.delete()
    return redirect('blogs')


def author_detail(request, id):
    """View showing the details of an author"""
    author = BlogAuthor.objects.get(id=id)
    context = {
        'author': author
    }
    return render(request, 'blog/author-detail.html', context)


def blog_like(request, id):
    """Like associated with a blog instance"""
    blog = get_object_or_404(Blog, id=id)
    like = BlogLike.objects.filter(user=request.user, post=blog)
    if like.exists():
        like[0].delete()
        return redirect('blog-detail', id=id)
    BlogLike.objects.create(user=request.user, post=blog)
    return redirect('blog-detail', id=id)

src/templates/blog/author-detail.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5 vh-100">
  <p class="display-6">Blogger: {{author.user.username}}</p>
  <h3 class="py-3">Bio</h3>  
  {{author.bio}}

  <h4>Blogs list</h4>
  <div>
    <ul class="list-unstyled">
      {% for blog in author.blog_set.all.reverse %}
      <li class="mb-3 text-muted small">
      <a  class="blog-list1 lead on-hover" href="{{ blog.get_absolute_url }}"> {{ blog.title }}</a></strong> ({{blog.post_date}})
      </li>
      {% endfor %}
    </ul>
  </div>

</div>
{% endblock %}

src/templates/blog/blog-create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container py-5">
    <div class="container py-2">
      <div class='col-md-6 offset-md-3'>
        <h3 class="py-1">Post a Blog</h3>
        <form method="post" enctype='multipart/form-data'>
          {% csrf_token %}
          {{ form|crispy }}
          {{ form.media }}
          <button type="submit" class="btn btn-info">Post Blog</button>
        </form>
      </div>
    </div>

</div>
{% endblock %}

src/templates/blog/blog-detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container py-5 mt-3">
  {% if user.is_authenticated and request.user.username == blog.author.user.username %}
          <span><a href="{% url 'blog-update' blog.id %}" class="btn btn-warning">Update BlogPost</a></span>
          {% if user.is_staff or request.user.username == blog.author.user.username %}
          <span><a href="{% url 'blog-delete' blog.id %}" class="btn btn-danger float-end">Delete Blogpost</a></span>
          {% endif %}
  {% endif %}

  <div class='row pt-4'>
    <div class='col-15 offset-0'>
    <div class='card' style='padding: 10px;'>
        <p class="display-6">{{ blog.title|title }}</p>
        {% if blog.thumbnail %}
        <img src="{{ blog.thumbnail.url }}" class="card-img-top" alt="..." width="107" height="700">
        {% endif %}
        <br>
        <div class="mb-3">
        <h5>{{ blog.content|safe }}</h5>
        </div>
        <div class="mb-3">
            <span class="me-3"><i class="fa fa-comments blog-list1"></i> {{ blog.get_comment_count }}</span>
            <span class="me-3"><i class="fa fa-eye blog-list1"></i> {{ blog.get_view_count }}</span>
            <span>
              <a class="text-muted" href="{{ blog.get_like_url }}">
                {% if request.user.is_authenticated %}
                <i class="fa-solid fa-hands-clapping">
                </i> {{ blog.get_like_count }}
                {% endif %}
              </a>
            </span>
            <span class='float-end text-muted'>Posted {{ blog.publish_date|timesince }} ago</span>
        </div>
        <div>
            {% if request.user.is_authenticated %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {{ form.media }}
                    <button class='btn btn-info' type='submit'>Post Comment</button>
                </form>
                <hr />
                <h5>Comments</h5>
                {% for comment in blog.blogcomment_set.all %}
                    <div>
                        <p>{{comment.commenter}}
                        <br />
                        {{ comment.content }}
                        <br />
                        <small class="text-muted">{{ comment.timestamp|timesince }} ago</small>
                        </p>
                    </div>
                {% endfor %}
            {% else %}
            <a href="{% url 'account_login' %}?next={{request.path}}" class="btn btn-primary btn-block">Login to comment</a>
            {% endif %}
        </div>
    </div>
    </div>
  </div>

</div>
{% endblock %}

src/templates/blog/blog-list.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5">
    {% block content_header %}
      {% if user.is_authenticated %}
      <p class="py-3">
        <a href="{% url 'blog-create' %}" class="btn btn-info">Create a new blog</a>
      </p>  
      {% endif%}
    {% endblock %}
    <h1 class="display-6 my-3">Latest blog posts</h1>

    {% if blog_list %}
    <ul class="list-unstyled">

      {% for blog in blog_list %}
      <li class="mb-3 text-muted small">
        <a class="lead on-hover text-dark" href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.publish_date|timesince}} ago) — <a class="text-muted" href="{% url 'author-detail' blog.author.id %}">{{ blog.author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no blogs.</p>
    {% endif %}
    
</div>
{% endblock %}

src/templates/blog/blog-post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class='col-md-6 offset-md-3'>
      <h3>Post a Blog</h3>
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

src/templates/blog/blog-update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="container py-5 my-2">
    <div class='col-md-6 offset-md-3'>
      <h3>Update your Blog</h3>
      <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}
        {{ form.media }}
        <button type="submit" class="btn btn-info">Update blog</button>
      </form>
    </div>
  </div>
{% endblock %}

src/templates/blog/blog_list.html
{% extends "base.html" %}

{% block content %}
    <h1>All blogs</h1>

    {% if blog_list %}
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.post_date}}) — <a href="{% url 'author-detail' blog.author.id %}">{{ blog.author }}</a>
        {# <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.post_date}}) — <a href="#">{{ blog.author }}</a> #}
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no blogs.</p>
    {% endif %}       
{% endblock %}

src/templates/blog/create-comment.html
{% extends "base.html" %}

{% block content %}
  <h1>Blog Reference: {{ blog.title }}</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}