src/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_blog, name='blogs'),
    path('create', views.blog_create, name='blog-create'),
    path('<int:id>/', views.blog_detail, name='blog-detail'),
    path('<int:id>/update', views.blog_update, name='blog-update'),
    path('<int:id>/delete', views.blog_delete, name='blog-delete'),
    path('author/<int:id>', views.author_detail, name='author-detail'),
    path('like/<int:id>/', views.blog_like, name='blog-like'),
]

src/forum/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.list_thread, name='forum'),
    path('<int:id>', views.thread_detail, name='thread-detail'),
    path('create', views.thread_create, name='thread-create'),
]

src/openSourceBookHub/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_library.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/forum/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.

class Thread(models.Model):
    """
    Model representing a thread.
    """
    title = models.CharField(max_length=1000)
    content = models.TextField(max_length=2000, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)


    def get_absolute_url(self):
        """
        Returns the url to access a particular forum instance.
        """
        return reverse('thread-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        len_title = 70
        if len(self.title) > len_title:
            titlestring = self.title[:len_title] + '...'
        else:
            titlestring = self.title
        return titlestring


class Discussion(models.Model):
    """
    Model representing a Discussion.
    """
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, default=None)
    content = models.CharField(max_length=1000)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String for representing the Model object."""
        len_comment = 70
        if len(self.content) > len_comment:
            commentstring = self.content[:len_comment] + '...'
        else:
            commentstring = self.content
        return commentstring

src/forum/forms.py
from django import forms
from .models import Thread, Discussion


class ThreadForm(forms.ModelForm):
    """Respresenting Thread Form"""
    class Meta:
        model = Thread
        fields = ('title', 'content',)

    def __init__(self, *args, **kwargs):
        super(ThreadForm, self).__init__(*args, **kwargs)
        self.fields['content'].required = False


class DiscussionForm(forms.ModelForm):
    """Respresenting a Discussion Form"""
    class Meta:
        model = Discussion
        fields = ('content',)

src/forum/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.utils.timesince import timesince
from django.shortcuts import render, get_object_or_404, redirect

from .forms import DiscussionForm, ThreadForm
from .models import Thread

# Create your views here.

def list_thread(request):
    """List all available threads"""
    threads = Thread.objects.all()
    context = {
        'threads': threads
    }
    return render(request, 'forum/thread-list.html', context)


def thread_detail(request, id):
    """View the details of a thread"""
    thread = get_object_or_404(Thread, id=id)
    
    if request.method == "POST":
        form = DiscussionForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.instance.thread = thread
            form.save()
        return redirect('thread-detail', id=id)
    else:
        form = DiscussionForm()


    context = {
        'form': form,
        'thread': thread
    }
    return render(request, 'forum/thread-detail.html', context)

def thread_create(request):
    """creating a thread"""
    form = ThreadForm()
    if request.method == "POST":
        form = ThreadForm(request.POST)
        if form.is_valid():
            author = get_object_or_404(User, username=request.user)
            form.instance.author =  author    
            form.save()
            id= form.instance.id
            return redirect('thread-detail', id=id)
    context = {
        'form': form
    }
    return render(request, 'forum/thread-create.html', context)

src/templates/forum/forum-create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class='col-md-6 offset-md-3'>
      <h3>Create a Forum</h3>
      <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

src/templates/forum/forum-detail.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</head>
<body>

<h2>{{forum.topic}}</h2>

<div id="display">

</div>

<script>
$(document).ready(function(){


setInterval(function(){
    $.ajax({
        type: 'GET',
      url : "{{forum.id}}/getMessages",
        success: function(response){
            console.log(response);
            $("#display").empty();
            for (var key in response.messages)
            {
                var temp="<div class='container darker'><b>"+
                        response.messages[key].commenter__username+"</b><p>"+
                        response.messages[key].message+"</p><span class='time-left'>"+
                        response.messages[key].timestamp+"</span></div>";
                $("#display").append(temp);
            }
        },
        error: function(response,){
          alert('An error occured')
        }
    });
},1000);
})
</script>


<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>
    
    {% if user.is_authenticated %}
    <form id="post-form">
        {% csrf_token %}
        <input type="text" name="message" id="message" width="100px" />
        <input type="submit" value="Send">
    </form>
    {% else %}
    <a href="{% url 'account_login' %}?next={{request.path}}" class="btn btn-primary btn-block">
      <input type="submit" value="Sign-in to send a message">
    </a>
    {% endif %}
</div>

</body>

<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'{{forum.id}}/send',
      data:{
        message:$('#message').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         //alert(data)
      }
    });
    document.getElementById('message').value = ''
  });
</script>

</html>

src/templates/forum/forum-list.html
{% extends "base.html" %}

{% block content %}
    {% block content_header %}
      {% if user.is_authenticated %}
      <p>
        <a href="{% url 'forum-create' %}" class="btn btn-primary">Create a new forum</a>
      </p>  
      {% endif%}
    {% endblock %}
    <h1>All Forums</h1>

    {% if forums %}
    <ul>

      {% for forum in forums %}
      <li>
        <a href="{{ forum.get_absolute_url }}">{{ forum.topic }}</a> ({{forum.date_created|timesince}} ago)</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no forums created yet.</p>
    {% endif %}       
{% endblock %}

src/templates/forum/thread-create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-4 my-1">
    <div class="top-bar bg-info px-5 py-1">
        <h1>
            Forum
        </h1>
    </div>
    <div class="main bg-light pb-5">
      <div class="container">
        <div class='col-md-6 offset-md-3 py-5'>
            <h3>Create a new Thread!</h3>
            <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info">Submit</button>
            </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

src/templates/forum/thread-detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container py-4 my-1">
    <div class="top-bar bg-info px-5 py-1">
        <h1>
            Forum
            <a href="{% url 'forum' %}" class="float-end text-light small text-decoration-none mt-1">Thread</a>
        </h1>    
    </div>
    <div class="main bg-light px-5 pb-5">
        <div class="header pt-3 pb-5">
          <h3 class="title pt-3">
           {{thread.title}}
          </h4>
          {% if thread.content %}
          <br>
          <div class="fs-5">
            {{thread.content}}
          </div>
          {% endif %}
          <div class="d-flex text-muted fst-italic">
              <p><small>
                {{thread.timestamp|timesince}} ago
              </small></p>
              <p class="mx-3"><small>
                {{thread.discussion_set.all.count}} comments
              </small></p>
          </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class="textspace">
          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class='btn btn-info mt-2 mb-5' type='submit'>Post comment</button>
          </form>
        </div>
        {% else %}
            <a href="{% url 'account_login' %}?next={{request.path}}" class="btn btn-secondary btn-block">Login to comment</a>
        {% endif %}
        <div class="mt-5">
          {% for comment in thread.discussion_set.all %} 
          <div class="comment-content">
            {{comment.content}}
          </div>
          <div class="d-flex text-muted fst-italic small">
            <p class="user">
              {{comment.author}}
            </p>
            <p class="mx-3">
             {{comment.timestamp}}
            </p>
          </div>
          {% endfor %}
        </div>
    </div>
  </div>
{% endblock %}

src/templates/forum/thread-list.html
{% extends "base.html" %}

{% block content %}
<div class="container py-4 my-1">
    <div class="top-bar bg-info px-5 py-1">
        <h1>
            Forum
            {% if user.is_authenticated %}
            <a href="{% url 'thread-create' %}" class="btn btn-light float-end mt-1">Create a new thread</a>
            {% else %}
            <a href="{% url 'account_login' %}?next={{request.path}}" class="btn btn-secondary btn-block float-end addmargin">Login to create a thread</a>
            {% endif%}
        </h1>
    </div>
    <div class="main bg-light px-3">
        <ol>
          {% for thread in threads %}
          <li class="row">
            <a class="text-decoration-none" href="{{ thread.get_absolute_url }}">
              <h4 class="text-dark pt-4 book">{{thread.title}}</h4>
              <div class="d-flex text-muted">
                <p class="timestamp">{{thread.timestamp|timesince}} ago</p>
                <p class="px-4">
                  {{thread.discussion_set.all.count}} comments
                </p>
              </div>
            </a>
          </li>
          {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}